### ISSUE TITLE
Repository names generated by the plugin conflict with maven-publish validation

### ISSUE THREAD

**Issue by kevinclark** [wpilibsuite/wpilib-repositories-plugin#3]
I'm on quite the yak shave. I'm trying to get shuffleboard to build on OpenJDK13 so I can write a widget, but [gradle 5 on OpenJDK13 blows up](https://github.com/gradle/gradle/issues/8681) (shuffleboard version [here](https://gist.github.com/kevinclark/16c0c1f6505d8dcc45de3f5f99ad0a48)) so I'm working on moving shuffleboard to a gradle 6 wrapper. But a gradle 6 wrapper pulls in a new maven-publish plugin and as of [May of 2019 the maven-publish plugin validates repository names](https://github.com/gradle/gradle/commit/70f7e9a4e0d241ff69e939e57bd54b663f8b1862#diff-a148fd7441406c4747f16a944b7f9895). The repo names generated by this plugin are [invalid](https://gist.github.com/kevinclark/a8f9442eea9d5bb37a53506854ad9959#file-gistfile1-txt-L37).

I'm happy to provide a patch (and will be doing so shortly), but wanted to give the context around why I'm doing so. I understand if you don't want to take this yet, but even if my other patches aren't taken, at some point wpilib is going to have to move to a later version of gradle and we'll run into this again. Might as get it out of the way, right?

**Comment by ThadHouse** [comment]
Closed by https://github.com/wpilibsuite/wpilib-repositories-plugin/pull/9
